version: 2

run:
  timeout: 5m
  tests: false
  allow-parallel-runners: true
  skip-dirs:
    - ^gen$
    - ^gen/
    - ^cmd/wallaby-bench$
    - ^cmd/wallaby-bench/
    - ^cmd/wallaby-bench-summary$
    - ^cmd/wallaby-bench-summary/
    - ^cmd/wallaby-spec-manifest$
    - ^cmd/wallaby-spec-manifest/
    - ^cmd/wallaby-spec-sync$
    - ^cmd/wallaby-spec-sync/
    - ^cmd/wallaby-speccheck$
    - ^cmd/wallaby-speccheck/
    - ^cmd/wallaby-tla-coverage$
    - ^cmd/wallaby-tla-coverage/
    - ^cmd/wallaby-trace-validate$
    - ^cmd/wallaby-trace-validate/
    - ^terraform/provider$
    - ^terraform/provider/
    - ^tools$
    - ^tools/

linters:
  enable:
    - asciicheck
    - bodyclose
    - errcheck
    - errorlint
    - gosec
    - govet
    - gocritic
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosec:
    exclude-generated: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    - path: ^(tests|examples|bench)/
      linters:
        - gosec
    - path: _test\.go
      linters:
        - gosec
    - path: ^gen/
      linters:
        - gofmt
        - goimports
        - govet
        - staticcheck
        - errcheck
        - gocritic
        - unparam
        - unconvert
        - unused
