run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - ineffassign
    - unused

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
