max_retries = 2
retry_wait_time = 2
accept = [200, 204, 206, 429]
exclude = [
  '^https?://localhost',
  '^https?://127\\.0\\.0\\.1',
  '^https?://[^/]*example\\.(com|org|net)',
  '^postgres://',
  '^grpc://',
]
