---
# {{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "wallaby.serviceAccountName" . }}'
  labels:
    app.kubernetes.io/name: '{{ include "wallaby.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
# {{ end }}
# {{ if .Values.workerServiceAccount.create }}
# {{ if .Values.workerServiceAccount.automountServiceAccountToken }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "wallaby.workerServiceAccountName" . }}'
  labels:
    app.kubernetes.io/name: '{{ include "wallaby.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: worker
automountServiceAccountToken: true
# {{ else }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "wallaby.workerServiceAccountName" . }}'
  labels:
    app.kubernetes.io/name: '{{ include "wallaby.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: worker
automountServiceAccountToken: false
# {{ end }}
# {{ end }}
