#!/bin/sh
set -eu

root=$(cd -- "$(dirname "$0")/.." && pwd)
output_root=${1:-$root}
mkdir -p "$output_root"
output_root=$(cd -- "$output_root" && pwd)

cd "$root"

: "${GOBIN:=$(go env GOPATH)/bin}"
export PATH="$GOBIN:$PATH"

generated="$output_root/docs/reference/generated"
rm -rf "$generated"
mkdir -p "$generated/go"
buf generate proto --template buf.gen.docs.yaml --include-imports --output "$output_root"
grpc_doc="$generated/grpc.md"
sed 's|(#google-protobuf-Timestamp)|(https://protobuf.dev/reference/protobuf/google.protobuf/#timestamp)|g' \
	"$grpc_doc" >"${grpc_doc}.tmp"
mv "${grpc_doc}.tmp" "$grpc_doc"

for package in certify connector pgstream schemaregistry spec stream wire; do
	output="$generated/go/${package}.md"
	temporary="${output}.tmp"
	gomarkdoc \
		--repository.url https://github.com/josephjohncox/WALlaby \
		--repository.default-branch main \
		--output "$temporary" \
		"./pkg/${package}"
	{
		printf '%s\n\n' '<!-- Generated by gomarkdoc. Edit the Go source comments instead. -->'
		sed 's#file:///Users/[^)]*#/blob/main#g' "$temporary"
	} >"$output"
	rm -f "$temporary"
done

# Normalize generator whitespace so generated references are stable and pass
# git diff --check on every platform.
for document in "$generated/grpc.md" "$generated/go/"*.md; do
	awk '
		{sub(/[[:space:]]+$/, ""); lines[NR]=$0}
		END {
			last=NR
			while (last > 0 && lines[last] == "") last--
			for (line=1; line <= last; line++) print lines[line]
		}
	' "$document" >"${document}.tmp"
	mv "${document}.tmp" "$document"
done
