#!/bin/sh
set -eu

GO=${GO:-go}
GO_TEST_VERBOSE=${GO_TEST_VERBOSE:-1}
GO_TEST_VERBOSE_FLAG=${GO_TEST_VERBOSE_FLAG:-}
if [ -z "$GO_TEST_VERBOSE_FLAG" ] && [ "$GO_TEST_VERBOSE" = "1" ]; then
	GO_TEST_VERBOSE_FLAG=-v
fi
IT_KIND=${IT_KIND:-${WALLABY_TEST_K8S_KIND:-1}}
IT_KEEP=${IT_KEEP:-0}
IT_KIND_CLUSTER=${IT_KIND_CLUSTER:-${KIND_CLUSTER:-wallaby-test}}
IT_KIND_NODE_IMAGE=${IT_KIND_NODE_IMAGE:-${KIND_NODE_IMAGE:-kindest/node:v1.35.0}}
IT_SERVICE_READY_TIMEOUT_SECONDS=${IT_SERVICE_READY_TIMEOUT_SECONDS:-240}
IT_RUN_FILTER=${IT_RUN_FILTER:-}
IT_COUNT=${IT_COUNT:-}
IT_PACKAGE_PARALLELISM=${IT_PACKAGE_PARALLELISM:-1}
IT_EXPECTED_HARNESS_PARTICIPANTS=${IT_EXPECTED_HARNESS_PARTICIPANTS:-$IT_PACKAGE_PARALLELISM}
INTEGRATION_PACKAGE=${INTEGRATION_PACKAGE:-./tests/...}

set -- "$GO" test -p "$IT_PACKAGE_PARALLELISM"
if [ -n "$GO_TEST_VERBOSE_FLAG" ]; then
	set -- "$@" "$GO_TEST_VERBOSE_FLAG"
fi
set -- "$@" "$INTEGRATION_PACKAGE" \
	-it-kind="$IT_KIND" \
	-it-keep="$IT_KEEP" \
	-it-k8s-kind-cluster="$IT_KIND_CLUSTER" \
	-it-k8s-kind-node-image="$IT_KIND_NODE_IMAGE" \
	-it-expected-harness-participants="$IT_EXPECTED_HARNESS_PARTICIPANTS"
if [ -n "$IT_RUN_FILTER" ]; then
	set -- "$@" -run "$IT_RUN_FILTER"
fi
if [ -n "$IT_COUNT" ]; then
	set -- "$@" -count="$IT_COUNT"
fi

export IT_VERBOSE=$GO_TEST_VERBOSE
export WALLABY_IT_VERBOSE=$GO_TEST_VERBOSE
export WALLABY_IT_SERVICE_READY_TIMEOUT_SECONDS=$IT_SERVICE_READY_TIMEOUT_SECONDS
exec "$@"
