package snowflake

import "strings"

// managedStreamCurrentSchemaDDL is the only accepted streaming control schema.
// It is provisioning SQL, not runtime auto-migration. Existing tables with the
// obsolete blind-upsert shape must be replaced before transport promotion.
func managedStreamCurrentSchemaDDL(cfg streamConfig) []string {
	channel := managedSnowflakeStreamQualifiedTable(cfg, cfg.channelStateTable)
	requests := streamRequestTable(cfg)
	return []string{
		"CREATE HYBRID TABLE " + channel + " (" + strings.Join([]string{
			"\"FLOW_INCARNATION_ID\" VARCHAR NOT NULL", "\"DESTINATION_REVISION_ID\" VARCHAR NOT NULL", "\"CHANNEL_NAME\" VARCHAR NOT NULL",
			"\"PIPE_NAME\" VARCHAR NOT NULL", "\"PIPE_REVISION\" VARCHAR NOT NULL", "\"CHANNEL_REVISION\" NUMBER(38,0) NOT NULL",
			"\"CONTINUATION_TOKEN\" VARCHAR NOT NULL", "\"COMMITTED_OFFSET_TOKEN\" VARCHAR NOT NULL", "\"LOGICAL_BATCH_ID\" VARCHAR NOT NULL",
			"\"ROWS_CONTENT_HASH\" VARCHAR(64) NOT NULL", "\"REQUEST_ID\" VARCHAR NOT NULL", "\"STATE_VERSION\" NUMBER(38,0) NOT NULL", "\"UPDATED_AT\" TIMESTAMP_TZ(9) NOT NULL",
			"CONSTRAINT \"WALLABY_STREAM_CHANNEL_PK\" PRIMARY KEY (\"FLOW_INCARNATION_ID\",\"DESTINATION_REVISION_ID\",\"CHANNEL_NAME\")",
		}, ", ") + ")",
		"CREATE HYBRID TABLE " + requests + " (" + strings.Join([]string{
			"\"REQUEST_ID\" VARCHAR NOT NULL", "\"FLOW_ID\" VARCHAR NOT NULL", "\"FLOW_INCARNATION_ID\" VARCHAR NOT NULL", "\"SOURCE_LINEAGE_ID\" VARCHAR NOT NULL",
			"\"DESTINATION_REVISION_ID\" VARCHAR NOT NULL", "\"LOGICAL_BATCH_ID\" VARCHAR NOT NULL", "\"POSITION_ID\" VARCHAR NOT NULL", "\"CONTENT_HASH\" VARCHAR(64) NOT NULL",
			"\"MANIFEST_HASH\" VARCHAR(64) NOT NULL", "\"ROWS_CONTENT_HASH\" VARCHAR(64) NOT NULL", "\"ROW_COUNT\" NUMBER(38,0) NOT NULL",
			"\"CHANNEL_NAME\" VARCHAR NOT NULL", "\"PIPE_NAME\" VARCHAR NOT NULL", "\"CHANNEL_REVISION\" NUMBER(38,0) NOT NULL", "\"PIPE_REVISION\" VARCHAR NOT NULL",
			"\"INPUT_CONTINUATION_TOKEN\" VARCHAR NOT NULL", "\"EXPECTED_PREVIOUS_COMMITTED_OFFSET_TOKEN\" VARCHAR NOT NULL", "\"REQUESTED_OFFSET_TOKEN\" VARCHAR NOT NULL", "\"RESPONSE_CONTINUATION_TOKEN\" VARCHAR NOT NULL",
			"\"COMMITTED_OFFSET_TOKEN\" VARCHAR NOT NULL", "\"GENERATION\" NUMBER(38,0) NOT NULL", "\"ACQUISITION_ID\" VARCHAR NOT NULL", "\"LEASE_EPOCH\" NUMBER(38,0) NOT NULL",
			"\"ATTEMPT\" NUMBER(38,0) NOT NULL", "\"PHASE\" VARCHAR NOT NULL", "\"PHASE_VERSION\" NUMBER(38,0) NOT NULL", "\"RESPONSE_KIND\" VARCHAR NOT NULL",
			"\"RESPONSE_EVIDENCE\" VARCHAR NOT NULL", "\"CREATED_AT\" TIMESTAMP_TZ(9) NOT NULL", "\"UPDATED_AT\" TIMESTAMP_TZ(9) NOT NULL",
			"CONSTRAINT \"WALLABY_STREAM_REQUEST_PK\" PRIMARY KEY (\"REQUEST_ID\")",
			"CONSTRAINT \"WALLABY_STREAM_REQUEST_ATTEMPT\" UNIQUE (\"FLOW_INCARNATION_ID\",\"DESTINATION_REVISION_ID\",\"LOGICAL_BATCH_ID\",\"ATTEMPT\")",
		}, ", ") + ")",
	}
}
